name = "cfspider"
main = "workers/workers.js"
compatibility_date = "2024-01-01"

# 启用 workers.dev
workers_dev = true

# 自定义域名
routes = [
  { pattern = "ip.kami666.xyz/*", zone_name = "kami666.xyz" }
]
